import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The docs sidebar is defined explicitly (not autogenerated) so the reading
 * order is a deliberate path: what Zynax is → run it → author a workflow →
 * how it works → the full CLI surface.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'getting-started',
    'workflows',
    'architecture',
    'cli',
  ],
};

export default sidebars;
